### PR TITLE
Support for file://

### PR DESCRIPTION
**Pull request by boludoz**

### CODE REVIEW

**Comment by boludoz** [comment]
You can add an additional check to detect if it is a file beforehand and add file:// to it.

**Comment by boludoz** [comment]
TODO: Add INSECURE = False

**Comment by rkbennett** [comment]
This one I'm going to push back on quite a bit just due to the fact that the stated purpose of this package is remote importing through memory. Is there a particular reason you're trying to import from a file?

**Comment by rkbennett** [comment]
Based on your issue you closed you seem to be under the impression that ZipImport is deprecated, but so far as I know only one of the functions it's using to do the import is deprecated and they have a plan to update that part of it. So if you're just wanting this functionality because ZipImport is deprecated, it actually isn't.

**Comment by boludoz** [comment]
The support for files also seems appropriate to me, what would be the main advantage and why did I add it? Because it serves to debug the code without having to upload it to the Internet.

**Comment by rkbennett** [comment]
This is where we diverge because I generally look at the testing should be built towards the purpose of the code. For example, when I do "local" testing, I already have python and http.server is in stdlib. So for local testing you just open another terminal an run `python -m http.server 8080` from the directory of your target file. Then when you run od_import you call it like this `od_import.add_remote_source("http://localhost:8080/myfile.zip", INSECURE=True)` that get's you able to call files on the local system while still using the network-based mechanisms of the tool. Also remove firewalls from the equation since localhost isn't typically subject to that level of scrutiny. That's a round-about way of saying I won't be adding file:// support, but I can certainly add documentation to the README that walks through how a typical testing environment would be set up.

**Comment by boludoz** [comment]
Nowadays even browsers support folder access, it would be a waste not to add this.

**Comment by boludoz** [comment]
image
It is incredibly simple and useful, there is nothing like this, it would be very useful.

**Comment by rkbennett** [comment]
> Nowadays even browsers support folder access, it would be a waste not to add this. The question is why not? 🙏 It is a simple implementation, keep in mind that you are also supporting SMB.

Yes, but SMB is a network protocol.

**Comment by boludoz** [comment]
> > Nowadays even browsers support folder access, it would be a waste not to add this. The question is why not? 🙏 It is a simple implementation, keep in mind that you are also supporting SMB.
> 
> Yes, but SMB is a network protocol.

Oh, how absolutely thrilling it is to hear that you’ve decided against adding support for file://. Truly, it’s a bold move to stick with the tried and true, to resist the siren call of innovation. After all, who needs progress when we can bask in the warm, comforting glow of the status quo?

Keep doing you, champ. I’m sure all your users are just over the moon about your steadfast commitment to not changing a thing. Bravo! 👏👏👏

**Comment by rkbennett** [comment]
While adding password protected zip functionality sounds interesting, this still doesn't fit with the general scheme or intent of this project. For the reasons I have mentioned as well as the fact that it sounds like it should be a path hook while this repo deals in meta hooks, I'm going to close this issue. There are other projects that implement that functionality on passworded zip imports such as [ArchiveImporter](https://github.com/Dakkaron/ArchiveImporter).

**Comment by boludoz** [comment]
> While adding password protected zip functionality sounds interesting, this still doesn't fit with the general scheme or intent of this project. For the reasons I have mentioned as well as the fact that it sounds like it should be a path hook while this repo deals in meta hooks, I'm going to close this issue. There are other projects that implement that functionality on passworded zip imports such as [ArchiveImporter](https://github.com/Dakkaron/ArchiveImporter).

Oh, absolutely! Because who needs password protection in this day and age? It's not like data security is a big deal or anything. And why would anyone want to add functionality to a project? That's just crazy talk! Let's just keep everything the way it is, because change is scary! 😄

**Comment by boludoz** [comment]
Joke ,I'm just kidding.

**Comment by boludoz** [comment]
> While adding password protected zip functionality sounds interesting, this still doesn't fit with the general scheme or intent of this project. For the reasons I have mentioned as well as the fact that it sounds like it should be a path hook while this repo deals in meta hooks, I'm going to close this issue. There are other projects that implement that functionality on passworded zip imports such as [ArchiveImporter](https://github.com/Dakkaron/ArchiveImporter).

Go to sleep and tell me how you wake up tomorrow, if you want to be my friend, just add this.

**Pull request closed without merging**
