### PR TITLE
Fix. IncompleteRead: urllib is more "reliable" now

### PR DESCRIPTION
**Pull request by boludoz**
Improved method for download

```
GET_FILE_MAX_ATTEMPTS = 3
GET_FILE_MAX_WAIT = 0.5
```

```
try:
    from httplib import IncompleteRead
except ImportError:
    from http.client import IncompleteRead
```

```
    for attemps in range(GET_FILE_MAX_ATTEMPTS):
        try:
            resp = opener(url).read()
            break
        except IncompleteRead as e:
            logging.info(e)
            if attemps == GET_FILE_MAX_ATTEMPTS - 1:
                raise e

        try:
            time.sleep(GET_FILE_MAX_WAIT)
        except OSError as e:
            logging.error(e)
            continue
```

That solves: Incomplete reading, a very common error, even in stable connections.

### CODE REVIEW

**Comment by boludoz** [comment]
You can also use request, but it means importing more things.

**Comment by rkbennett** [comment]
Thanks for the PR, I'll start looking through the commits.

**Comment by rkbennett** [comment]
@boludoz Is this something you are running into quite a bit? Have you tried doing an http downgrade to HTTP/1.0 vs running attempts in a loop?

**Comment by boludoz** [comment]
It's happening very often, I have good internet. It is a well-known error. I realized late that your package included it, otherwise I would have used request.

**Comment by boludoz** [comment]
[> Thanks for the PR, I'll start looking through the commits.



> @boludoz Is this something you are running into quite a bit? Have you tried doing an http downgrade to HTTP/1.0 vs running attempts in a loop?
](https://github.com/rkbennett/od_import/pull/1/files)

**Comment by boludoz** [comment]
> @boludoz Is this something you are running into quite a bit? Have you tried doing an http downgrade to HTTP/1.0 vs running attempts in a loop?

https://github.com/rkbennett/od_import/pull/1/files

**Comment by rkbennett** [comment]
Does it only happen when pulling from specific stacks (IIS, etc)? I'm just trying to narrow down the potential root cause. I assume based on the PR this is only happening to you when you're using the directory of helper?

**Comment by boludoz** [comment]
> Does it only happen when pulling from specific stacks (IIS, etc)? I'm just trying to narrow down the potential root cause. I assume based on the PR this is only happening to you when you're using the directory of helper?

I was investigating more and the problem is the defective http servers, I am precisely downloading a zip from github.

**Comment by rkbennett** [comment]
Hey, sorry to throw a bit of a wrench into this PR, but it made me think that I needed a refactor of the http helpers so that items that are directly related to urllib requests can be modified in one place vs 6+. I am still wanting to research the issue you're running into though. Would you be able to create a quick issue with the specifics of how you're environment (python version, package hosting technology, etc)? I'd greatly appreciate it.

**Comment by boludoz** [comment]
of course

**Comment by boludoz** [comment]
```
import od_import
with od_import.remote_source('https://github.com/boludoz/jubilant-umbrella/blob/main/seleniumbase_.zip?raw=True'):
  from seleniumbase import BaseCase
  BaseCase.main(__name__, __file__)

  class CoffeeCartTest(BaseCase):
      def test_coffee_cart(self):
          self.open("https://seleniumbase.io/coffee/")
          self.assert_title("Coffee Cart")
          self.click('div[data-sb="Cappuccino"]')
          self.click('div[data-sb="Flat-White"]')
          self.click('div[data-sb="Cafe-Latte"]')
          self.click('a[aria-label="Cart page"]')
          self.assert_exact_text("Total: $53.00", "button.pay")
          self.click("button.pay")
          self.type("input#name", "Selenium Coffee")
          self.type("input#email", "test@test.test")
          self.click("button#submit-payment")
          self.assert_text("Thanks for your purchase.", "#app .success")
```

**Comment by rkbennett** [comment]
@boludoz is this a separate issue? I thought you had said you could pull from github?

**Comment by boludoz** [comment]
> @boludoz is this a separate issue? I thought you had said you could pull from github?

The problem is when downloading any type of file.

**Comment by boludoz** [comment]
Replacing urllib with request worked for me, taking advantage of the fact that you have setup.py, we could add request there.

**Comment by boludoz** [comment]
Considerations: your code would require python 3.7+ if you add request, plus you would need to import request (although it is an almost canonical library).

**Comment by rkbennett** [comment]
Hmmm, so here's the thing with when you use github.com, it does imports based on repo structure. Can you try taking the contents of seleniumbase_.zip and making them their own repo? So essentially make a repo called seleniumbase, and then make a subdirectory of it called seleniumbase and put the contents of your zip file into there.

**Comment by rkbennett** [comment]
Do you have selenium installed on the box your running this on?

**Comment by boludoz** [comment]
> Hmmm, so here's the thing with when you use github.com, it does imports based on repo structure. Can you try taking the contents of seleniumbase_.zip and making them their own repo? So essentially make a repo called seleniumbase, and then make a subdirectory of it called seleniumbase and put the contents of your zip file into there.

https://stackoverflow.com/questions/14442222/how-to-handle-incompleteread-in-python

**Comment by rkbennett** [comment]
@boludoz I'm testing this right now, and there are no incomplete reads in my testing

**Comment by rkbennett** [comment]
I am going to close this PR because this is starting to look more like it needs to be submitted as an issue. If you can go and create an issue for this we can discuss it better there vs creating a really long thread in a PR that isn't code related.

**Comment by rkbennett** [comment]
Closing this as the code has been refactored and more research should be done as to what the actual issue is. Please open an issue for this and we can dive further into it.

**Comment by boludoz** [comment]
> I am going to close this PR because this is starting to look more like it needs to be submitted as an issue. If you can go and create an issue for this we can discuss it better there vs creating a really long thread in a PR that isn't code related.

I should place the zip and that should work.

**Comment by rkbennett** [comment]
> > I am going to close this PR because this is starting to look more like it needs to be submitted as an issue. If you can go and create an issue for this we can discuss it better there vs creating a really long thread in a PR that isn't code related.
> 
> I should place the zip and that should work now, believe me, I don't have any problem, it is an error on some http servers.

Please create an Issue and we can discuss this further there.

**Comment by boludoz** [comment]
> > > I am going to close this PR because this is starting to look more like it needs to be submitted as an issue. If you can go and create an issue for this we can discuss it better there vs creating a really long thread in a PR that isn't code related.
> > 
> > 
> > I should place the zip and that should work now, believe me, I don't have any problem, it is an error on some http servers.
> 
> Please create an Issue and we can discuss this further there.

image

**Pull request closed without merging**
